language: php
php:
  - '7.0'

services:
  - mysql

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - mysql -e 'create database jg;'
  - composer install
  - php bin/console doctrine:schema:create --env=test

script: phpunit

notifications:
    on_success: never
    on_failure: always