<?php

namespace TurniejBundle\Repository;

/**
 * EntryTournamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryTournamentRepository extends \Doctrine\ORM\EntityRepository
{
}
