<?php

namespace TurniejBundle\Repository;

/**
 * TeamM8Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamM8Repository extends \Doctrine\ORM\EntityRepository
{
}
