<?php

namespace TurniejBundle\Repository;

/**
 * TurniejeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurniejeRepository extends \Doctrine\ORM\EntityRepository
{
}
