<?php

namespace AppBundle\Repository;

/**
 * FeaturedEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
