imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl
    mem_upload: '%kernel.root_dir%/../web/assets/mem'

framework:
    #esi:             ~
    translator: { fallbacks: [pl] }
#    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    profile:
        form:
            type: AppBundle\Form\ProfileFormType
    registration:
        confirmation:
            enabled: true
    resetting:
        email:
            from_email:
                address:        noreply@jestemgraczem.pl
                sender_name:    Reset JestemGraczem.pl
    from_email:
        address:        noreply@jestemgraczem.pl
        sender_name:    JestemGraczem

# Payum configuration
payum:
    security:
        token_storage:
            TurniejBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        TurniejBundle\Entity\Payment: { doctrine: orm }

    gateways:
        offline:
            factory: offline
        paypal:
            factory: paypal_express_checkout
            username:  "%paypal_username%"
            password:  "%paypal_password%"
            signature: "%paypal_signature%"
            sandbox: "%paypal_sandbox%"

#SonataSeoBundle
sonata_seo:
    encoding:         UTF-8
    sitemap:
        services:
            - app.sitemap_service
    page:
        title:            JestemGraczem
#        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             jestem,graczem,gry,tworzone,z,pasji,portal,poświęcony,graczom,jestemgraczem,turnieje,stream,youtube,reklama
                description:          JestemGraczem.pl jest to pierwszy w Polsce portal poświęcony graczom, a nie samym grom!
                robots:               index, follow
                author:               Otlet
                viewport:             width=device-width, initial-scale=1, shrink-to-fit=no
                'twitter:card':        summary
                'twitter:site':        "@PanOtlet"
                'twitter:title':       JestemGraczem.pl
                'twitter:description': JestemGraczem.pl jest to pierwszy w Polsce portal poświęcony graczom, a nie samym grom!
            property:
                # Facebook application settings
                'fb:app_id':          '1792775277616619'
                'fb:admins':          PanOtlet, 100000499973060, TheOtlet

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       "JestemGraczem.pl"
                'og:description':     "JestemGraczem.pl jest to pierwszy w Polsce portal poświęcony graczom, a nie samym grom!"
                'og:type':            "website"
                'og:image':           "http://i.imgur.com/Ims7cz0.png"

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7
                'cache-control': 'public'
                'cache-control': 'max-age=86400'

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            'xmlns:fb':           http://www.facebook.com/2008/fbml

# Vich Upload Bundle
vich_uploader:
    db_driver: orm
    mappings:
        news:
            uri_prefix:         /assets/images/news
            upload_destination: '%kernel.root_dir%/../web/assets/images/news'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

# Twig
twig:
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

# KNP Pagination
knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
#        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig
        pagination: material/pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

# Security Bundle
nelmio_security:
    # signs/verifies all cookies
    signed_cookie:
        names: ['*']
    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY
    # prevents redirections outside the website's domain
    external_redirects:
        abort: false
        log: true

    # prevents inline scripts, unsafe eval, external scripts/images/styles/frames, etc
    csp:
        hosts:
            - localhost
            - jestemgraczem.pl
        content_types: []
        report_logger_service: monolog.logger.security
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false
            report-uri: %router.request_context.base_url%/nelmio/csp/report
            default-src:
                - 'self'
                - beam.pro
                - use.fontawesome.com
                - vjs.zencdn.net
                - localhost
                - api.twitch.tv
            style-src:
                - 'self'
                - 'unsafe-inline'
                - vjs.zencdn.net
                - use.fontawesome.com
            script-src:
                - 'self'
                - 'unsafe-inline'
                - 'unsafe-eval'
                - www.google-analytics.com
                - vjs.zencdn.net
                - ajax.googleapis.com
                - use.fontawesome.com
                - cdn.onesignal.com
                - apis.google.com
                - connect.facebook.net
                - www.youtube.com
            frame-src:
                - www.youtube.com
                - connect.facebook.net
                - jestemgraczem.onesignal.com
                - beam.pro
                - apis.google.com
                - accounts.google.com
                - staticxx.facebook.com
                - www.facebook.com
                - player.twitch.tv
            font-src:
                - 'self'
                - 'unsafe-inline'
                - use.fontawesome.com
                - 'data:'
            img-src:
                - 'self'
                - facebook.com
                - flickr.com
                - i.imgur.com
                - uploads.beam.pro
                - static-cdn.jtvnw.net
                - www.gravatar.com
                - img.youtube.com
                - www.google-analytics.com
                - ssl.gstatic.com
                - www.facebook.com
            block-all-mixed-content: true # defaults to false, blocks HTTP content over HTTPS transport
            upgrade-insecure-requests: true # defaults to false, upgrades HTTP requests to HTTPS transport

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # forces Microsoft's XSS-Protection with
    # its block mode
    xss_protection:
        enabled: true
        mode_block: true

    # forces HTTPS handling, don't combine with flexible mode
    # and make sure you have SSL working on your site before enabling this
    forced_ssl:
        hsts_max_age: 2592000
        hsts_subdomains: true

    # flexible HTTPS handling, read the detailed config info
    # and make sure you have SSL working on your site before enabling this
#    flexible_ssl:
#        cookie_name: auth
#        unsecured_logout: false