imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl
    mem_upload: '%kernel.root_dir%/../web/assets/mem'

framework:
    #esi:             ~
    translator: { fallbacks: [pl] }
#    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    profile:
        form:
            type: AppBundle\Form\ProfileFormType
    registration:
        confirmation:
            enabled: true
    resetting:
        email:
            from_email:
                address:        noreply@jestemgraczem.pl
                sender_name:    Reset JestemGraczem.pl
    from_email:
        address:        noreply@jestemgraczem.pl
        sender_name:    JestemGraczem

#SonataSeoBundle
sonata_seo:
    encoding:         UTF-8
    page:
        title:            JestemGraczem
#        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             jestem,graczem,gry,tworzone,z,pasji,portal,poświęcony,graczom,jestemgraczem,turnieje,stream,youtube,reklama
                description:          JestemGraczem.pl jest to pierwszy w Polsce portal poświęcony graczom, a nie samym grom!
                robots:               index, follow
                viewport:             width=device-width, initial-scale=1, shrink-to-fit=no
            property:
                # Facebook application settings
                'fb:app_id':          '1792775277616619'
                'fb:admins':          PanOtlet, 100000499973060, TheOtlet

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       "JestemGraczem.pl"
                'og:description':     "JestemGraczem.pl jest to pierwszy w Polsce portal poświęcony graczom, a nie samym grom!"
                'og:type':            "website"

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            'xmlns:fb':           http://www.facebook.com/2008/fbml

easy_admin:
    entities:
        CMS:
            class: AppBundle\Entity\CMS
            list:
                fields:
                    - 'id'
                    - { property: 'title', label: 'admin.title'}
                    - { property: 'url', label: 'admin.url'}
                    - { property: 'text', label: 'admin.text'}
        Mems:
            class: AppBundle\Entity\Meme
            list:
                fields:
                    - 'id'
                    - { property: 'accept', label: 'admin.accept'}
                    - { property: 'title', label: 'admin.title'}
                    - { property: 'source', label: 'admin.source'}
                    - { property: 'url', type: 'image', base_path: 'http://localhost/jg/web/assets/mem/', label: 'admin.img' }
        YouTube:
            class: AppBundle\Entity\Video
            list:
                fields:
                    - 'id'
                    - { property: 'title', label: 'admin.title'}
                    - { property: 'accept', label: 'admin.accept'}
                    - { property: 'videoid', label: 'admin.id'}
                    - { property: 'videoid', type: 'image', base_path: 'http://img.youtube.com/vi/%1/mqdefault.jpg', label: 'admin.img' }
        Uzytkownicy:
            class: AppBundle\Entity\User
            list:
                fields:
                    - 'id'
                    - { property: 'username', label: 'admin.username'}
                    - { property: 'email', label: 'admin.email'}
                    - { property: 'last_login', label: 'admin.lastlogin', type: 'datetime'}
                    - { property: 'locked', label: 'admin.locked'}
                    - { property: 'enabled', label: 'admin.enabled'}
        RSS: AppBundle\Entity\News
    site_name: 'JG Admin'
    design:
        brand_color: '#9C27B0'