app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#TurniejBundle

turniej:
    resource: "@TurniejBundle/Controller/"
    type:     annotation
    prefix:   /turniej

team:
    resource: "@TurniejBundle/Controller/TeamController.php"
    type:     annotation
    prefix:   /druzyny

division:
    resource: "@TurniejBundle/Controller/DivisionController.php"
    type:     annotation
    prefix:   /dywizja

#API

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

api.lol:
    resource: "@ApiBundle/Controller/LoLController.php"
    type:     annotation
    prefix:   /api/lol

#Default

cms:
    resource: "@AppBundle/Controller/CMSController.php"
    type:     annotation
    prefix:   /cms

mem:
    resource: "@AppBundle/Controller/MemeController.php"
    type:     annotation
    prefix:   /mem

status:
    resource: "@AppBundle/Controller/StatusController.php"
    type:     annotation
    prefix:   /status

#GameBundle

game:
    resource: "@GameBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /game

game.lol:
    resource: "@GameBundle/Controller/LoLController.php"
    type:     annotation
    prefix:   /game/lol

game.csgo:
    resource: "@GameBundle/Controller/CSGOController.php"
    type:     annotation
    prefix:   /game/csgo

game.hots:
    resource: "@GameBundle/Controller/HotSController.php"
    type:     annotation
    prefix:   /game/hots


#SYSTEM

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
