app:
    resource: "@AppBundle/Controller/"
    type:     annotation
#    schemes:  [https]

#nelmio_security:
#    path:     /nelmio/csp/report
#    defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
#    methods:  [POST]

#TurniejBundle

#turniej:
#    resource: "@TurniejBundle/Controller/"
#    type:     annotation
#    prefix:   /turniej
#
#team:
#    resource: "@TurniejBundle/Controller/TeamController.php"
#    type:     annotation
#    prefix:   /druzyny
#
#division:
#    resource: "@TurniejBundle/Controller/DivisionController.php"
#    type:     annotation
#    prefix:   /dywizja

#NewsBundle

news:
    resource: "@NewsBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /news

#API

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api
#    schemes:  [https]

#Default

cms:
    resource: "@AppBundle/Controller/CMSController.php"
    type:     annotation
    prefix:   /cms

mem:
    resource: "@AppBundle/Controller/MemeController.php"
    type:     annotation
    prefix:   /mem

status:
    resource: "@AppBundle/Controller/StatusController.php"
    type:     annotation
    prefix:   /status

#SYSTEM

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /siemaeniu
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"
payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"
