app:
    resource: "@AppBundle/Controller/"
    type:     annotation

nelmio_security:
    path:     /nelmio/csp/report
    defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
    methods:  [POST]

#TurniejBundle

turniej:
    resource: "@TurniejBundle/Controller/"
    type:     annotation
    prefix:   /turniej

team:
    resource: "@TurniejBundle/Controller/TeamController.php"
    type:     annotation
    prefix:   /druzyny

division:
    resource: "@TurniejBundle/Controller/DivisionController.php"
    type:     annotation
    prefix:   /dywizja

#NewsBundle

news:
    resource: "@NewsBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /news

#API

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

api.lol:
    resource: "@ApiBundle/Controller/LoLController.php"
    type:     annotation
    prefix:   /api/lol

#Default

cms:
    resource: "@AppBundle/Controller/CMSController.php"
    type:     annotation
    prefix:   /cms

mem:
    resource: "@AppBundle/Controller/MemeController.php"
    type:     annotation
    prefix:   /mem

status:
    resource: "@AppBundle/Controller/StatusController.php"
    type:     annotation
    prefix:   /status

#GameBundle

game:
    resource: "@GameBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /game

game.lol:
    resource: "@GameBundle/Controller/LoLController.php"
    type:     annotation
    prefix:   /game/lol

game.csgo:
    resource: "@GameBundle/Controller/CSGOController.php"
    type:     annotation
    prefix:   /game/csgo

game.hots:
    resource: "@GameBundle/Controller/HotSController.php"
    type:     annotation
    prefix:   /game/hots

game.wow:
    resource: "@GameBundle/Controller/WoWController.php"
    type:     annotation
    prefix:   /game/wow

game.overwatch:
    resource: "@GameBundle/Controller/OverwatchController.php"
    type:     annotation
    prefix:   /game/overwatch

game.hs:
    resource: "@GameBundle/Controller/HearthstoneController.php"
    type:     annotation
    prefix:   /game/hearthstone

game.wot:
    resource: "@GameBundle/Controller/WoTController.php"
    type:     annotation
    prefix:   /game/wot

game.gta:
    resource: "@GameBundle/Controller/GTAController.php"
    type:     annotation
    prefix:   /game/gta

game.dota:
    resource: "@GameBundle/Controller/DotaController.php"
    type:     annotation
    prefix:   /game/dota

game.pokemon:
    resource: "@GameBundle/Controller/PokemonController.php"
    type:     annotation
    prefix:   /game/pokemon

# WykopBundle
wykop:
    resource: "@WykopBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /mikroblog


#SYSTEM

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /siemaeniu
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"
payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"
