turniej:
    resource: "@TurniejBundle/Controller/"
    type:     annotation
    prefix:   /turniej

team:
    resource: "@TurniejBundle/Controller/TeamController.php"
    type:     annotation
    prefix:   /druzyny

division:
    resource: "@TurniejBundle/Controller/DivisionController.php"
    type:     annotation
    prefix:   /dywizja

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

cms:
    resource: "@AppBundle/Controller/CMSController.php"
    type:     annotation
    prefix:   /cms

mem:
    resource: "@AppBundle/Controller/MemeController.php"
    type:     annotation
    prefix:   /mem

status:
    resource: "@AppBundle/Controller/StatusController.php"
    type:     annotation
    prefix:   /status

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
