turniej:
    resource: "@TurniejBundle/Controller/"
    type:     annotation
    prefix:   /turniej

team:
    resource: "@TurniejBundle/Controller/TeamController.php"
    type:     annotation
    prefix:   /team

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
