security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            remember_me:
                secret:   '%secret%'
                lifetime: 604800
                path:     /
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
#        - { path: ^/, requires_channel: https, host: jestemgraczem\.pl$ }
#        - { path: ^/, requires_channel: https, host: localhost$ }
#        - { path: ^/*, requires_channel: https }
        - { path: ^/admin/, requires_channel: https, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/add, role: ROLE_USER }
        - { path: ^/status*, role: ROLE_USER }
#        - { path: ^/turniej/dolacz/*, role: ROLE_USER }
#        - { path: ^/turniej/.*/edit, role: ROLE_USER }
#        - { path: ^/turniej/.*/invite*, role: ROLE_USER }
        - { path: ^/turniej/.*/*, role: ROLE_ADMIN }