# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.sitemap_service:
        class: AppBundle\Model\SitemapIterator
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    #SiteMap!
    app.sitemap.mem_post_subscriber:
        class:     AppBundle\EventListener\SitemapMemPostSubscriber
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }
    app.sitemap.cms_subscriber:
        class:     AppBundle\EventListener\SitemapCmsPostSubscriber
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }
    app.sitemap.news_post_subscriber:
        class:     NewsBundle\EventListener\SitemapNewsPostSubscriber
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }